
const D=window.COURSE_DATA; const view=document.getElementById('view'); const nav=document.getElementById('classNav');
const state={route:'home',done:new Set(JSON.parse(localStorage.getItem('pycourse_done')||'[]'))};
function save(){localStorage.setItem('pycourse_done',JSON.stringify([...state.done]));updateProgress()}
function updateProgress(){const total=D.course.length; const pct=Math.round(state.done.size/total*100);document.getElementById('progressText').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%'}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function mapPath(page){return D.maps[String(page)]||D.maps[page]}
function buildNav(){nav.innerHTML='<button data-r="home">⌂ Inicio</button>'+D.course.map(c=>`<button data-r="class-${c.num}">${String(c.num).padStart(2,'0')} · ${esc(c.title)} ${state.done.has(c.num)?'<span class="done-badge">✓</span>':''}</button>`).join('')+'<button data-r="close">✓ Cierre y ruta futura</button>';nav.querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.r));}
function setActive(){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.r===state.route));}
function home(){document.getElementById('crumb').textContent='Inicio'; view.innerHTML=`<div class="fade"><section class="hero"><div><div class="eyebrow">Curso interactivo · 11 clases</div><h1>Python para negocios, datos e IA</h1><p>Un recorrido práctico desde los fundamentos de programación hasta el análisis de datos, visualización, aplicaciones con Tkinter e integración responsable con inteligencia artificial.</p><div class="cta-row"><button class="btn primary" onclick="go('class-1')">Comenzar clase 1 →</button><button class="btn secondary" onclick="openSearch()">Buscar un tema</button></div><div class="stat-grid"><div class="stat"><strong>11</strong><span>clases</span></div><div class="stat"><strong>92</strong><span>páginas fuente</span></div><div class="stat"><strong>Práctico</strong><span>mercadeo y administración</span></div></div></div><div class="hero-card"><img src="${mapPath(2)}" alt="Mapa del curso"></div></section><div class="section-title"><h2>Ruta de aprendizaje</h2><p>Puedes entrar a cualquier clase. Tu progreso se guarda en este navegador.</p></div><div class="class-grid">${D.course.map(c=>`<article class="class-card" onclick="go('class-${c.num}')"><span class="class-no">${c.num}</span><h3>${esc(c.title)}</h3><p>${esc(c.desc)}</p></article>`).join('')}</div></div>`}
function pointHtml(p,i){return `<div class="point"><strong>${i+1}.</strong> ${esc(p)}</div>`}
function moduleHtml(m,i){const code=m.code&&m.code.length?`<div class="codebox"><button class="copy" onclick="copyCode(this)">Copiar</button><pre><code>${esc(m.code.join('\n'))}</code></pre></div>`:'';const pts=m.points&&m.points.length?`<div class="lesson-points">${m.points.map(pointHtml).join('')}</div>`:'';return `<details class="module" ${i===0?'open':''}><summary><span class="module-index">${i+1}</span><div><h3>${esc(m.title)}</h3><p>${esc(m.subtitle||'Contenido de la clase')}</p></div></summary><div class="content">${pts}${code}</div></details>`}
function classView(c){document.getElementById('crumb').textContent=`Clase ${c.num}`; const q=c.quiz;view.innerHTML=`<div class="fade"><section class="class-head"><div><span class="tag">Clase ${c.num}</span><h1>${esc(c.title)}</h1><p>${esc(c.desc)}</p><div class="cta-row"><button class="btn primary" onclick="markDone(${c.num})">${state.done.has(c.num)?'✓ Clase completada':'Marcar como completada'}</button><button class="btn secondary" onclick="document.querySelector('.module').scrollIntoView()">Ver contenidos ↓</button></div></div><div class="class-map"><img src="${mapPath(c.map_page)}" alt="Mapa visual de la clase ${c.num}"></div></section><div class="module-list">${c.modules.map(moduleHtml).join('')}</div><section class="quiz"><span class="tag">Autoevaluación</span><h3>${esc(q.q)}</h3><div class="quiz-options">${q.opts.map((o,i)=>`<button onclick="answerQuiz(this,${c.num},${i})">${esc(o)}</button>`).join('')}</div><div class="feedback" id="fb-${c.num}">Elige una respuesta.</div></section><div class="class-footer"><button class="btn secondary" onclick="go('${c.num===1?'home':'class-'+(c.num-1)}')">← ${c.num===1?'Inicio':'Clase '+(c.num-1)}</button><button class="btn primary" onclick="go('${c.num===11?'close':'class-'+(c.num+1)}')">${c.num===11?'Ir al cierre':'Clase '+(c.num+1)} →</button></div></div>`}
function closeView(){document.getElementById('crumb').textContent='Cierre';view.innerHTML=`<div class="fade"><div class="section-title"><span class="tag">Cierre</span><h2>De usuario de software a creador de soluciones</h2><p>El material cierra con práctica continua, portafolio y rutas para seguir avanzando.</p></div><div class="closing-grid">${D.closing.map(m=>`<article class="closing-card"><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p>${m.points.slice(0,10).map(p=>`<p>• ${esc(p)}</p>`).join('')}</article>`).join('')}</div><div class="cta-row"><button class="btn primary" onclick="go('home')">Volver al inicio</button><button class="btn secondary" onclick="resetProgress()">Reiniciar progreso</button></div></div>`}
function go(r){state.route=r;location.hash=r;document.getElementById('sidebar').classList.remove('open');render()}
function render(){buildNav();setActive();if(state.route==='home')home();else if(state.route==='close')closeView();else{const n=+state.route.split('-')[1];classView(D.course.find(c=>c.num===n)||D.course[0])}window.scrollTo({top:0,behavior:'smooth'})}
function markDone(n){state.done.add(n);save();render()}
function answerQuiz(btn,n,i){const q=D.course.find(c=>c.num===n).quiz;const wrap=btn.parentElement;wrap.querySelectorAll('button').forEach((b,j)=>{b.disabled=true;if(j===q.a)b.classList.add('good');else if(j===i)b.classList.add('bad')});document.getElementById('fb-'+n).textContent=(i===q.a?'Correcto. ':'Revisa este punto. ')+q.why}
function copyCode(btn){navigator.clipboard.writeText(btn.parentElement.querySelector('code').innerText);btn.textContent='Copiado ✓';setTimeout(()=>btn.textContent='Copiar',1200)}
function resetProgress(){if(confirm('¿Reiniciar el progreso guardado en este navegador?')){state.done.clear();save();render()}}
function openSearch(){document.getElementById('searchModal').classList.add('open');document.getElementById('searchInput').focus();search('')}
function closeSearch(){document.getElementById('searchModal').classList.remove('open')}
function search(q){q=q.toLowerCase().trim();const rows=[];D.course.forEach(c=>{const hay=[c.title,c.desc,...c.modules.flatMap(m=>[m.title,m.subtitle,...m.points,...m.code])].join(' ').toLowerCase();if(!q||hay.includes(q))rows.push(c)});document.getElementById('searchResults').innerHTML=rows.length?rows.map(c=>`<div class="search-result" onclick="closeSearch();go('class-${c.num}')"><strong>Clase ${c.num}: ${esc(c.title)}</strong><br><small>${esc(c.desc)}</small></div>`).join(''):'<div class="search-result">Sin resultados.</div>'}
function toggleTheme(){const d=document.documentElement;const next=d.dataset.theme==='dark'?'light':'dark';d.dataset.theme=next;localStorage.setItem('pycourse_theme',next)}
window.go=go;window.markDone=markDone;window.answerQuiz=answerQuiz;window.copyCode=copyCode;window.openSearch=openSearch;window.closeSearch=closeSearch;window.resetProgress=resetProgress;
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('themeBtn').onclick=toggleTheme;document.getElementById('resetBtn').onclick=resetProgress;document.getElementById('searchBtn').onclick=openSearch;document.getElementById('closeSearch').onclick=closeSearch;document.getElementById('searchInput').oninput=e=>search(e.target.value);document.getElementById('fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.getElementById('searchModal').onclick=e=>{if(e.target.id==='searchModal')closeSearch()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});document.documentElement.dataset.theme=localStorage.getItem('pycourse_theme')||'light';state.route=(location.hash||'#home').slice(1);updateProgress();render();
